
EXE ?= .js
CC = emcc
TCC_SRCS = 
ISOCLINE_SRCS = 

GLOBAL := -s EXPORT_ALL=1
CFLAGS := -fPIC -DNDEBUG $(GLOBLAL) $(CFLAGS)
LDFLAGS := -s SINGLE_FILE=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s INITIAL_MEMORY=2GB -s ALLOW_MEMORY_GROWTH=1 -s EXPORT_ES6=1 -s ENVIRONMENT=web -s MAIN_MODULE=2 -s EXPORTED_RUNTIME_METHODS=FS $(GLOBLAL) $(LDFLAGS) 

include makefile

