
EXE ?= .js
CC = emcc
TCC_SRCS = 
ISOCLINE_SRCS = 

CFLAGS := -fPIC -DNDEBUG $(CFLAGS)
LDFLAGS := -s TOTAL_STACK=16MB -s INITIAL_MEMORY=2GB -s ALLOW_MEMORY_GROWTH=1 -s SINGLE_FILE=1 -s EXIT_RUNTIME=0 -s MODULARIZE=1 -s EXPORT_ES6=1 -s ENVIRONMENT=web -s ALLOW_MEMORY_GROWTH=1 -s MAIN_MODULE=1 $(LDFLAGS) 

include makefile

