
#define VM_USE_NUM f32

#define EXPAND(...) __VA_ARGS__

#define VM_LANG_PAKA_NUM_TAG_i8(...)  VM_TAG_I8 
#define VM_LANG_PAKA_NUM_TAG_i16(...) VM_TAG_I16
#define VM_LANG_PAKA_NUM_TAG_i32(...) VM_TAG_I32
#define VM_LANG_PAKA_NUM_TAG_i64(...) VM_TAG_I64

#define VM_LANG_PAKA_NUM_TAG_f32(...) VM_TAG_F32
#define VM_LANG_PAKA_NUM_TAG_f64(...) VM_TAG_F64

#define VM_LANG_PAKA_NUM_FIELD VM_USE_NUM

#define VM_LANG_PAKA_MACRO_CONCAT2I(x, y) x ## y
#define VM_LANG_PAKA_MACRO_CONCAT2(x, y) CONCAT2I(x, y)

#define VM_LANG_PAKA_NUM_TAG CONCAT2(VM_LANG_PAKA_NUM_TAG_, VM_USE_NUM)()
