
EXE ?= .js
CC = emcc
TCC_SRCS = 
ISOCLINE_SRCS =

CFLAGS := -fPIC $(CFLAGS)
LDFLAGS := -s BINARYEN_ASYNC_COMPILATION=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s ALLOW_MEMORY_GROWTH=1 -s EXPORT_ES6=1 -s ENVIRONMENT=worker -s MAIN_MODULE=2 -s EXPORTED_RUNTIME_METHODS="['FS','callMain']" $(LDFLAGS) 

include makefile

