
EXE ?= .js
CC = emcc
TCC_SRCS =
CFLAGS_TB =

CFLAGS := -fPIC $(CFLAGS)
LDFLAGS := -s BINARYEN_ASYNC_COMPILATION=0 -s ALLOW_MEMORY_GROWTH=1 -s MODULARIZE=1 -s EXPORT_ES6=1 -s ENVIRONMENT=worker -s MAIN_MODULE=2 -s EXPORTED_RUNTIME_METHODS="['FS','callMain']" $(LDFLAGS) 

include core.mak
