#pragma once

#include "lib.h"

enum
{
  VM_OPCODE_EXIT,
  VM_OPCODE_REG,
  VM_OPCODE_JUMP,
  VM_OPCODE_DJUMP,
  VM_OPCODE_FUNC,

  VM_OPCODE_CALL,
  VM_OPCODE_DCALL,
  VM_OPCODE_ADDR,
  VM_OPCODE_RET,

  VM_OPCODE_PUTCHAR,
  
  VM_OPCODE_FTOS,
  VM_OPCODE_FINT,
  VM_OPCODE_FRAC,
  VM_OPCODE_FADD,
  VM_OPCODE_FSUB,
  VM_OPCODE_FMUL,
  VM_OPCODE_FDIV,
  VM_OPCODE_FMOD,
  VM_OPCODE_FBB,
  VM_OPCODE_FBEQ,
  VM_OPCODE_FBLT,

  VM_OPCODE_SINT,
  VM_OPCODE_SNEG,
  VM_OPCODE_STOF,
  VM_OPCODE_SADD,
  VM_OPCODE_SSUB,
  VM_OPCODE_SMUL,
  VM_OPCODE_SDIV,
  VM_OPCODE_SMOD,
  VM_OPCODE_SBB,
  VM_OPCODE_SBEQ,
  VM_OPCODE_SBLT,
};

typedef uint32_t vm_opcode_t;
