#pragma once

#include "lib.h"

enum
{
  VM_OPCODE_EXIT,
  VM_OPCODE_REG,
  VM_OPCODE_JUMP,
  VM_OPCODE_DJUMP,
  VM_OPCODE_FUNC,

  VM_OPCODE_INT,
  VM_OPCODE_UADD,
  VM_OPCODE_USUB,
  VM_OPCODE_UMUL,
  VM_OPCODE_UDIV,
  VM_OPCODE_UMOD,
  VM_OPCODE_UBB,
  VM_OPCODE_UBEQ,
  VM_OPCODE_UBLT,
  
  VM_OPCODE_CALL,
  VM_OPCODE_DCALL,
  VM_OPCODE_INTF,
  VM_OPCODE_RET,

  VM_OPCODE_PUTCHAR,
  
  VM_OPCODE_CONS,
  VM_OPCODE_GETCAR,
  VM_OPCODE_GETCDR,
  VM_OPCODE_SETCAR,
  VM_OPCODE_SETCDR,

  VM_OPCODE_FTOU,
  VM_OPCODE_UTOF,
  VM_OPCODE_FINT,
  VM_OPCODE_FRAC,
  VM_OPCODE_FADD,
  VM_OPCODE_FSUB,
  VM_OPCODE_FMUL,
  VM_OPCODE_FDIV,
  VM_OPCODE_FMOD,
  VM_OPCODE_FBB,
  VM_OPCODE_FBEQ,
  VM_OPCODE_FBLT,

  VM_OPCODE_MAX1,
};

typedef uint32_t vm_opcode_t;
