#if !defined(VM_HEADER_IR_TAG)
#define VM_HEADER_IR_TAG

enum {
    VM_TAG_NIL,
    VM_TAG_BOOL,
    VM_TAG_SINT8,
    VM_TAG_SINT16,
    VM_TAG_SINT32,
    VM_TAG_SINT64,
    VM_TAG_UINT8,
    VM_TAG_UINT16,
    VM_TAG_UINT32,
    VM_TAG_UINT64,
    VM_TAG_F32,
    VM_TAG_F64,
    VM_TAG_BLOCK,
};

#endif
